shell = "zsh"

[plugins.zsh_autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh_completions]
github = "zsh-users/zsh-completions"

# zsh_syntax_highlighting は最後に書く

[plugins.zsh_syntax_highlighting]
github = "zsh-users/zsh-syntax-highlighting"
